---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: enableansiblecentos8
    image: registry.gitlab.com/dvonessen/docker-ansible-nonroot-centos:8
    pre_build_image: true
  - name: enableansibledebian10
    image: registry.gitlab.com/dvonessen/docker-ansible-nonroot-debian:10
    pre_build_image: true
  - name: enableansibleubuntu2004
    image: registry.gitlab.com/dvonessen/docker-ansible-nonroot-ubuntu:20.04
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
